### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by eric-f** [UBC-MDS/DSCI_522_wine-quality-predictors#27]
__Mechanics__ 
- [x] Might want to add version number for the packages in the dependency section.
- [x] the example of running the scripts by command line is quite busy with many lines. Maybe just pick one example for each script and state clearly what they do and how they depend on other scripts
- [x] Could have explain what are the expected inputs and outputs of the scripts. Say, some scripts takes more than 2 arguments and it is unclear what these arguments are.

__Others__
- [x] Try to have more discussions within the github issues? Right now, the messages are mostly just notifications. 

__Report__
- [x] Good that you have listed the variables but maybe put it in a table for easy reading. Would be nice to have a summary table of the variables. 
- [x] Barplots could be condensed a bit and smaller to improve flow of document. Would be nice to know exact counts.

**Comment by lyiris22** [comment]
Thank you for the feedback! Here are some ideas of improvements I will do on my part:

1. Add package version number in the dependency section
2. Make the examples more concise
3. Explain the inputs and outputs in the scripts
4. Add exact count to the barplots

For those that are related to the final report, I will discuss with Reza about how to do them.

**Comment by lyiris22** [comment]
Hi @reza-bagheri ,

I have made a pull request that responds to the issues:
- Version number in README
- File structure in README
- Make command examples more concise
- Make input arguments clearer
- Adjust the image size

Please take a look at the pull request and check if it's ok to merge. Also it will be great if you can try the Makefile pipeline in your local repo to see if it works well. Thanks!

**Comment by lyiris22** [comment]
For the summary table I guess either is fine.
Maybe we can add the counts for each quality/target. I can get the numbers for that. Is it just for the clean data?

**Comment by reza-bagheri** [comment]
Do you know how to add the counts on top of each bar in the bar plot? I had seen a similar graph in the viz course.

**Comment by reza-bagheri** [comment]
I think it can be for the cleaned data

**Comment by lyiris22** [comment]
I only found a way to do that with adjusting the text on each, not sure if it can be consistent in all data since our bar plot R script is used for many different data, but the position of the text has to be accurate.

**Comment by reza-bagheri** [comment]
OK, can you send me the numbers? I will make a table.

**Comment by lyiris22** [comment]
Sure. In addition, do you remember in which lecture of viz you saw that graph? Just for a reference.

**Comment by reza-bagheri** [comment]
Sorry I can't remember right now

**Comment by lyiris22** [comment]
No worry. Also, do you need numbers of clean data for both 3 and 4 targets?

**Comment by reza-bagheri** [comment]
Yes, both of them and for both wines.

**Comment by lyiris22** [comment]
Okay! I'll do it now.

**Comment by reza-bagheri** [comment]
I have found a stack overflow thread explaining how to put numbers on the bars. Can you take a look?
https://stackoverflow.com/questions/12018499/how-to-put-labels-over-geom-bar-for-each-bar-in-r-with-ggplot2/12019601

**Comment by lyiris22** [comment]
I think it works! I'll try to apply it to all the graphs and add a reference.

**Comment by lyiris22** [comment]
I have rendered the new graphs with numbers, and will upload to my fork. Please check my fork to see if there can be any improvements before I submit a pull request.

**Comment by reza-bagheri** [comment]
Sure

**Comment by reza-bagheri** [comment]
Please let me know when you uploaded it

**Comment by reza-bagheri** [comment]
> 
> 
> **Mechanics**
> 
>     * [x]  Might want to add version number for the packages in the dependency section.
> 
>     * [x]  the example of running the scripts by command line is quite busy with many lines. Maybe just pick one example for each script and state clearly what they do and how they depend on other scripts
> 
>     * [x]  Could have explain what are the expected inputs and outputs of the scripts. Say, some scripts takes more than 2 arguments and it is unclear what these arguments are.
> 
> 
> **Others**
> 
>     * [x]  Try to have more discussions within the github issues? Right now, the messages are mostly just notifications.
> 
> 
> **Report**
> 
>     * [x]  Good that you have listed the variables but maybe put it in a table for easy reading. Would be nice to have a summary table of the variables.
> 
>     * [x]  Barplots could be condensed a bit and smaller to improve flow of document. Would be nice to know exact counts.

We have made all the requested changes. A new feature table was added. Observation numbers were added to the barplots and they were resized.

**Comment by lyiris22** [comment]
As mentioned above, we also add version numbers to dependencies, make examples more concise, give more detailed explanations to input and output.
I had made a new pull request with minor changes in README. Can we close the issue after this?

**Comment by reza-bagheri** [comment]
I just merged it. Good job!. I am going to close the issue.
